apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terminal.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "terminal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        checksum/terminal-manager-config: {{ include (print $.Template.BasePath "/controller-configmap.yaml") . | sha256sum }}
        {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        control-plane: controller-manager
        {{- include "terminal.labels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "terminal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          command:
            - /manager
          args:
            - --health-probe-bind-address=:{{ .Values.controller.service.health.port }}
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --config-file-path=/config.yaml
          env:
            - name: TERMINAL_SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: {{ .Values.platform.tlsRejectUnauthorized | quote }}
          image: "{{ .Values.controller.image }}"
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.controller.service.health.port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.controller.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.controller.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controller.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          volumeMounts:
            {{- with .Values.controller.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: terminal-manager-config
              mountPath: /config.yaml
              subPath: config.yaml
      terminationGracePeriodSeconds: 10
      affinity:
        {{- if .Values.controller.affinity }}
        {{- toYaml .Values.controller.affinity | nindent 8 }}
        {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: control-plane
                      operator: In
                      values:
                        - controller-manager
                topologyKey: kubernetes.io/hostname
        {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.controller.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: terminal-manager-config
          configMap:
            name: {{ include "terminal.fullname" . }}-manager-config
