apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "terminal.labels" . | nindent 4 }}
  name: {{ include "terminal.fullname" . }}-controller-manager-health-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.controller.service.health.port }}
    protocol: TCP
    targetPort: health
  selector:
    control-plane: controller-manager
