apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "terminal-frontend.fullname" . }}-test-health"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminal-frontend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:8.10.1
      command:
        - curl
        - --fail
        - --silent
        - --show-error
        - "http://{{ include "terminal-frontend.fullname" . }}:{{ .Values.frontend.service.port }}/healthz"
